### PR TITLE
Update Good Cyber Security List: Modify/Remove bad links or non-existent content -- rationale available.

### PR DESCRIPTION
**Pull request by reachchrisyoung**
To Whom It May Concern:

Having reviewed roughly 198 records, the following recommendations were acted upon...

32 Link Removals.
4 Link Modifications (Some with modified titles)
Please view this resource, if needed, for amendment rationale and ongoing project progress.

(https://docs.google.com/spreadsheets/d/1qQn8x59ddANmnjNxJ1COLGqI_E6JJZFxPpvTEvJ3NRg/edit?usp=sharing
)

Respectfully submitted,

Chris Young
Participating Member, VetSec

### CODE REVIEW

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 151 Additional Line Items Reviewed...
19 Amendments Recommended:
19 Removals
0 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 255 Additional Line Items Reviewed...
38 Amendments Recommended:
37 Removals
1 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 188 Additional Line Items Reviewed...
31 Amendments Recommended:
29 Removals
2 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 117 Additional Line Items Reviewed...
23 Amendments Recommended:
22 Removals
1 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 163 Additional Line Items Reviewed...
30 Amendments Recommended:
29 Removals
1 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 241 Additional Line Items Reviewed...
21 Amendments Recommended:
21 Removals
0 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 261 Additional Line Items Reviewed...
22 Amendments Recommended:
22 Removals
0 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Temporary conflict; conflict resolved by deleting spaces within the code.  Changes were accepted after deleting 2 sections of approximately 4 to 5 white spaces each; changes were accepted by GitHub and no conflicts with the base branch were alerted to.

**Review by tylerwhardy — APPROVED** [review]

**Pull request merged**
