### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by reachchrisyoung**
To Whom It May Concern:

Having reviewed roughly 50 records, the following recommendations were acted upon...

1. 10 Amendments, encompassing:
a. 8 Removals
b. 2 Modifications (Some title modifications, some link modifications)

Please view this resource, if needed, for amendment rationale and ongoing project progress:
(https://docs.google.com/spreadsheets/d/1qQn8x59ddANmnjNxJ1COLGqI_E6JJZFxPpvTEvJ3NRg/edit?usp=sharing
)

Respectfully submitted,

Chris Young
Participating Member, VeteranSec

### CODE REVIEW

**Comment by reachchrisyoung** [comment]
1st Pull Request.

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 77 Additional Line Items Reviewed...
23 Amendments Recommended:
16 Removals
7 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 68 Additional Line Items Reviewed...
21 Amendments Recommended:
9 Removals
12 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 159 Additional Line Items Reviewed...
22 Amendments Recommended:
13 Removals
9 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 140 Additional Line Items Reviewed...
12 Amendments Recommended:
10 Removals
2 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 124 Additional Line Items Reviewed...
13 Amendments Recommended:
8 Removals
5 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 39 Additional Line Items Reviewed...
7 Amendments Recommended:
6 Removals
1 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 204 Additional Line Items Reviewed...
37 Amendments Recommended:
36 Removals
1 Modifications (Some caption changes, some source link changes)

**Comment by reachchrisyoung** [comment]
Update -- Time: NOW!

Over Roughly 80 Additional Line Items Reviewed...
17 Amendments Recommended:
16 Removals
1 Modifications (Some caption changes, some source link changes)

**Review by tylerwhardy — APPROVED** [review]

**Pull request merged**
